// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9g7cyjPkkQQ1x7Xx49mKl8WzyMgr2_uU',
    appId: '1:119605886758:web:a72760f4377f263d880be7',
    messagingSenderId: '119605886758',
    projectId: 'flutter-course-e93f5',
    authDomain: 'flutter-course-e93f5.firebaseapp.com',
    storageBucket: 'flutter-course-e93f5.appspot.com',
    measurementId: 'G-EJTG4DZ9YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqXSVAjRWc84Z95K36T9HXE_N5wi2yT4',
    appId: '1:119605886758:android:04a7ba34d9c01e70880be7',
    messagingSenderId: '119605886758',
    projectId: 'flutter-course-e93f5',
    storageBucket: 'flutter-course-e93f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIk_k2JMnxECeRk3ni1ZRc33PVLGg9SaI',
    appId: '1:119605886758:ios:9d39e54696c7f06d880be7',
    messagingSenderId: '119605886758',
    projectId: 'flutter-course-e93f5',
    storageBucket: 'flutter-course-e93f5.appspot.com',
    iosBundleId: 'com.example.flutterCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIk_k2JMnxECeRk3ni1ZRc33PVLGg9SaI',
    appId: '1:119605886758:ios:31d4ff2cd892c77c880be7',
    messagingSenderId: '119605886758',
    projectId: 'flutter-course-e93f5',
    storageBucket: 'flutter-course-e93f5.appspot.com',
    iosBundleId: 'com.example.flutterCourse.RunnerTests',
  );
}
